### PR TITLE
Store custom networks

### PR DESCRIPTION
**Pull request by arch1995**
Refs: -- https://toruslabs.atlassian.net/browse/PD-42

### CODE REVIEW

**Review by lionellbriones — APPROVED** [review]
lgmt

**Comment by chaitanyapotti** [comment]
the default networks will always be there. store only custom networks in state.
use a getter for merging custom + default ones as supportedNetworks

**Review by himanshuchawla009 — APPROVED** [review]
lgtm

**Review by chaitanyapotti — APPROVED** [review]
lgtm

**Pull request merged**
