### PR TITLE
allow zero gas fees for custom chains

### PR DESCRIPTION
**Pull request by arch1995**
Refs -- https://toruslabs.atlassian.net/browse/PD-1090

### CODE REVIEW

**Comment by chaitanyapotti** [comment]
Did you check the embed side as well?
What about controllers? do they allow sending tx with zero fees?

**Comment by himanshuchawla009** [comment]
- instead of doing it for all custom networks, I changed it to support zero gas fee only if the blockchain itself returns gas price as zero for the selected network which is happening by default. 

- We don't need to do it for eip1193 chains since logically eip1193 chains should never have zero gas price. 

- Tested with both wallet and embed side. I used the following network config to test, this chain has zero gas price feature :-

  RPC: https://node.taisys.dev/rpc or https://node.taisys.dev/taisys/rpc
  ChainID: 1068

**Comment by arch1995** [comment]
Agreed, LGTM

**Review by himanshuchawla009 — APPROVED** [review]
lgtm

**Pull request merged**
