### PR TITLE
initial hookup

### PR DESCRIPTION
**Pull request by lionellbriones**

### CODE REVIEW

**Comment by himanshuchawla009** [comment]
there is 2-3 sec of lag between i enter eth amount and the max transaction fee shows up. @lionellbriones  we should improve this

**Comment by himanshuchawla009** [comment]
also we should poll for base fee on tx page...

**Comment by himanshuchawla009** [comment]
Screenshot 2021-08-11 at 10 22 31 AM

confirmation screen shows wrong tx fee and cost values, also we should round of USD values while showing them correctly.

**Comment by himanshuchawla009** [comment]
> there is 2-3 sec of lag between i enter eth amount and the max transaction fee shows up. @lionellbriones we should improve this

fixed

**Comment by himanshuchawla009** [comment]
> gas fee polling should update input and text fields values dynamically, currently it is polling but values are not getting updated on UI.

fixed

**Comment by himanshuchawla009** [comment]
> Screenshot 2021-08-11 at 10 22 31 AM
> 
> confirmation popup shows wrong tx fee and cost values, also we should round of USD values while showing them correctly.

fixed

**Review by chaitanyapotti — APPROVED** [review]
lgtm. Pls address the mentioned stuff

**Pull request merged**
