### PR TITLE
Update controller tests

### PR DESCRIPTION
**Pull request by iamonuwa**

### CODE REVIEW

**Comment by chaitanyapotti** [comment]
Can you add more tests here.?
This is a good start.

**Comment by iamonuwa** [comment]
Absolutely, I'll update it.

**Comment by chaitanyapotti** [comment]
# [Codecov](https://codecov.io/gh/torusresearch/torus-website/pull/876?src=pr&el=h1) Report
> Merging [#876](https://codecov.io/gh/torusresearch/torus-website/pull/876?src=pr&el=desc) into [develop](https://codecov.io/gh/torusresearch/torus-website/commit/8965fc4c2831c90cf44c119f4bd937a91fc5171a&el=desc) will **increase** coverage by `1.20%`.
> The diff coverage is `n/a`.

[Impacted file tree graph](https://codecov.io/gh/torusresearch/torus-website/pull/876?src=pr&el=tree)

```diff
@@             Coverage Diff             @@
##           develop     #876      +/-   ##
===========================================
+ Coverage    60.05%   61.26%   +1.20%     
===========================================
  Files           37       37              
  Lines         2406     2406              
===========================================
+ Hits          1445     1474      +29     
+ Misses         961      932      -29     
```


| [Impacted Files](https://codecov.io/gh/torusresearch/torus-website/pull/876?src=pr&el=tree) | Coverage Δ | |
|---|---|---|
| [app/src/controllers/MessageManager.js](https://codecov.io/gh/torusresearch/torus-website/pull/876/diff?src=pr&el=tree#diff-YXBwL3NyYy9jb250cm9sbGVycy9NZXNzYWdlTWFuYWdlci5qcw==) | `79.66% <0.00%> (+1.69%)` | :arrow_up: |
| [app/src/controllers/AssetsController.js](https://codecov.io/gh/torusresearch/torus-website/pull/876/diff?src=pr&el=tree#diff-YXBwL3NyYy9jb250cm9sbGVycy9Bc3NldHNDb250cm9sbGVyLmpz) | `13.70% <0.00%> (+2.41%)` | :arrow_up: |
| [app/src/controllers/AssetsContractController.js](https://codecov.io/gh/torusresearch/torus-website/pull/876/diff?src=pr&el=tree#diff-YXBwL3NyYy9jb250cm9sbGVycy9Bc3NldHNDb250cmFjdENvbnRyb2xsZXIuanM=) | `71.73% <0.00%> (+54.34%)` | :arrow_up: |

------

[Continue to review full report at Codecov](https://codecov.io/gh/torusresearch/torus-website/pull/876?src=pr&el=continue).
> **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta)
> `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> Powered by [Codecov](https://codecov.io/gh/torusresearch/torus-website/pull/876?src=pr&el=footer). Last update [8965fc4...1fc6876](https://codecov.io/gh/torusresearch/torus-website/pull/876?src=pr&el=lastupdated). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments).

**Comment by chaitanyapotti** [comment]
Done

**Pull request closed without merging**
