### PR TITLE
Continue login with existing account

### PR DESCRIPTION
**Pull request by tainguyentt**

### CODE REVIEW

**Comment by chaitanyapotti** [comment]
Just show email even if it's not google or passwordless
if email is not available, don't show

**Comment by tainguyentt** [comment]
> Just show email even if it's not google or passwordless if email is not available, don't show

Sure, I'll check again. Not sure if there is any way to detect if the verifierID is email or just a random string.

**Comment by tainguyentt** [comment]
image

**Comment by tainguyentt** [comment]
image

**Review by chaitanyapotti — APPROVED** [review]
lgtm

**Pull request merged**
